// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urhynhrijvowibsllgny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyaHluaHJpanZvd2lic2xsZ255Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NzM0MzAsImV4cCI6MjA3MzM0OTQzMH0.JQ_E8T1WOL8Y_wIjJSs-_mAphwVelNfvsy5NCoXKvOg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});